# Generated by Django 3.0.4 on 2021-06-15 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0004_auto_20210603_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestedCalories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calo', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reco', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
